language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "cd check_mariadb_slaves && pip install -r requirements.txt"
# command to run tests
script: "python -m unittest tests"
